### ISSUE TITLE
Fields for BDPROTO

### ISSUE THREAD

**Issue by EitanGrossman** [bdproto/bdproto#15]
ID - We should merge them all, but later. UZ has 1-15, we stated new ones from 16. Since we should go through the original data too, we can merge them once they've been vetted.
LanguageFamilyRoot/Family/Classification: we should drop all but Family unless there is a reason to keep them all. This should be taken automatically if possibly from Glottolog.
TimeDepth etc - I think that we only need one field for this, and another for the reference source. As for how to proceed, I suggest we ask experts for a reliable ref or pc. I can handle this, as I bother people regularly by mail.
Homeland - same.
BibTexKey, FileName, Squib - why not a single entry?
LanguageCode - why do we need this if we have the Glottocode? Can we drop it?
Syllable structure - I don't think we'll have this for many languages, so I suggest we drop it, or otherwise have a fixed choice of data to be entered, otherwise the data is likely to be messy.
Region - how is this different from homeland? Can we drop it? If it is different, can we move it next to homeland?
Allophone - in many cases, some variation is given (g~gh), could this be used for this, and if so, how does one select the variant? Here the issue isn't really allophony, though, it's generally uncertainty as which is to be reconstructed.
Another - we probably need a tag for marginal phonemes (i.e., phonemes in parentheses in the doculect).

**Comment by bambooforest** [comment]
todo: once we've decided on the fields:

[ ] update the current raw data
[ ] update the aggregation script

**Comment by EitanGrossman** [comment]
*Ok.
*Is
*This
*How 
*You 
*Do 
*That?

**Comment by EitanGrossman** [comment]
- 1. Fields
- 2. ID
- 3. Etc
- 4.
