### ISSUE TITLE
Need a way to distinguish duplicate entries

### ISSUE THREAD

**Issue by bambooforest** [bdproto/bdproto#24]
- this could be by adding a column `LanguageName` with a standardized way of naming the inventories (so as to be able to easily identify duplicate entries) and replacing the current `LanguageName` with something like `SourceLanguageName`

- or it could be by assigning a Glottocode to each and every inventory

this should be done in the g-spreadsheet for the time being

**Comment by EitanGrossman** [comment]
Done. I did it according to your first suggestion. Glottocodes next up.
