### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by EitanGrossman** [bdproto/bdproto#30]
Are 2013 and 2014 duplicates? Looks like the same source.

**Comment by bambooforest** [comment]
@EitanGrossman 

https://github.com/bdproto/bdproto/blob/master/src/ancient-near-east/AnNeEa-inventories.csv#L422-L447

**Comment by EitanGrossman** [comment]
Got it. I'll update the metadata table.

Eitan Grossman
Associate Professor, Department of Linguistics
Chair, Department of Linguistics
Hebrew University of Jerusalem
Tel: +972 2 588 3809
Fax: +972 2 588 1224
