### ISSUE TITLE
165 - Proto-Irish 

### ISSUE THREAD

**Issue by EitanGrossman** [bdproto/bdproto#36]
Is this just Goedelic?

**Comment by macleginn** [comment]
On Tue, May 5, 2020, at 12:33 AM, Eitan Grossman wrote:
> 
> 
> Is this just Goedelic?

Goedelic is Irish + Scottish Gaelic, but Old Irish is older than the Goedelic split, which happened at some point in the Middle Ages, so Proto-Irish is just Proto-Irish.

**Comment by EitanGrossman** [comment]
Marked the Glottocode as NA. I wonder if this is different from the languages called "Pre-X."
