### ISSUE TITLE
Conversion for Americanist transcription?

### ISSUE THREAD

**Issue by EitanGrossman** [bdproto/bdproto#56]
Do you have a conversion table or the like for Americanist transcriptions? I don't always know what the glyphs are supposed to represent in IJAL etc, where they don't always use IPA.

**Comment by bambooforest** [comment]
https://en.wikipedia.org/wiki/Americanist_phonetic_notation ?

**Comment by EitanGrossman** [comment]
Cool, hope this will help avoid mistakes...

Eitan Grossman
Associate Professor, Department of Linguistics
Chair, Department of Linguistics
Hebrew University of Jerusalem
Tel: +972 2 588 3809
Fax: +972 2 588 1224

**Comment by bambooforest** [comment]
Maybe this is also helpful @EitanGrossman 

https://clts.clld.org/
